### ISSUE TITLE
Differences when compared to https://github.com/scottyab/secure-preferences?

### ISSUE THREAD

**Issue by stkent** [PDDStudio/EncryptedPreferences#2]
I see that this library is based on [AESCrypt-Android](https://github.com/scottyab/AESCrypt-Android) by scottyab. scottyab also offers a library that securely wraps `SharedPreferences` called [secure-preferences](https://github.com/scottyab/secure-preferences), based on his fork of [java-aes-crypto](https://github.com/scottyab/java-aes-crypto). It's not clear to me 1) why the two wrapper libraries are based on slightly different crypto libraries, and 2) what the impact of this difference may be. I would appreciate any light you can shed on why one might choose to use `EncryptedPreferences` rather than `secure-preferences`, or vice versa. Many thanks!

**Comment by tuzhenlei** [comment]
I saw this library used AES/256 bit key but the library developed by scottyab used AES/128 bit key. And  use this library, you can add a listener to observe the key changed.

**Comment by PDDStudio** [comment]
Actually, there are a lot of different libraries for several use cases. I didn't have a look at scottyab's library yet, so I can't tell you whether and/or what the differences are.
