### ISSUE TITLE
Change encryption password

### ISSUE THREAD

**Issue by ZaydelEduard** [PDDStudio/EncryptedPreferences#5]
How we can change encryption password?

**Comment by PDDStudio** [comment]
@ZaydelEduard you have to specify a password when instantiating a new `EncryptedPreferences` object :
`EncryptedPreferences encryptedPreferences = new EncryptedPreferences.Builder(this).withEncryptionPassword("password").build();`

Or did you want to change the password during runtime? Therefore you've to migrate all saved entries (which requires the old password) to a new `EncryptedPreferences` instance (created with the new password)

**Comment by ZaydelEduard** [comment]
@PDDStudio Yep, will be great to change password during runtime. For example after get password from server, and migrate all data what is been saved to new sharedpref with new password. It's possible ?

**Comment by PDDStudio** [comment]
@ZaydelEduard as with the default `SharedPreferences` you can use `getAllKeys()` and then call `EncryptedPreferences#forceDeleteExistingPreferences()`. After that, all previous saved settings are deleted, so make sure to hold a (local) reference to them during migration. Then you can create a new `EncryptedPreferences` instance and import your previous local referenced data.

**Comment by ZaydelEduard** [comment]
@PDDStudio Maybe you can add method to your library somithing like EncryptedPreferences.changePassword(Sring old, String new)? 
It can be very usefully feature.

**Comment by PDDStudio** [comment]
@ZaydelEduard sure, I can put it on my to-do list. Thanks for your proposal!

**Comment by ZaydelEduard** [comment]
@PDDStudio Thanks, i'll wait for new version of your library!

**Comment by PDDStudio** [comment]
I'm not quite sure whether this is possible to be handled by the library itself. When migrating the data to a new EncryptedPreferences instance they have to be decrypted before. Decryption requires knowing the Type of each value (e.g String, Integer, Boolean, etc) which the library doesn't know.

**Comment by PDDStudio** [comment]
Closing this one as there has been no further feedback for 3 years
